### ISSUE TITLE
Undefined (mode)

### ISSUE THREAD

**Issue by CommanderB** [CFenner/MagicMirror-LocalTransport-Module#1]
I'm getting 

undefined
in 8 mins
undefined 
in 28 mins 
etc 

when using my transit route `origin: Larchmont, NY`, `destination: Grand Central Terminal, , NY`

If I use the examples of `Mannheim HBF` to `Frankfurt HBF`, I get 

ICE in an hour
RE in 2 hours
1CE in an hour

**Comment by CFenner** [comment]
I'm sorry for that, I did't do a lot of testing. I'll have a look at it. You're also welcome put your hands on it yourself.

**Comment by CFenner** [comment]
Would you like to have `New Haven` displayed there?

**Comment by CommanderB** [comment]
New Haven is the name of the train line, so yes, that would be consistent. Thanks.

I did start to look at the code, and I did get it working with routes on London busses, but not the NY Metro North.

Thank you for this module - Having this data is the raison d'etre for my mirror. I had started poking around but JS is not my forte.

**Comment by CFenner** [comment]
Thanks, just send the commits to fix it. 

[SamLewis0602](https://github.com/SamLewis0602) did most of the work, I just put the data in the right place :)
