### ISSUE TITLE
Getting correct Station names

### ISSUE THREAD

**Issue by Dom1n1c** [CFenner/MagicMirror-LocalTransport-Module#11]
If have some Problems getting the correct station name.
This might be caused by special characters:

```
api_key: 'Key',
destination: 'Köln Hbf',
destination: 'Düsseldorf Hbf',
maximumEntries: 3,
maxWalkTime: 10,
displayStationLength: -1,
displayWalkType: 'none',
displayArrival: false,
language: 'de'
```

Düsseldorf,
Köln,
Köln Süd
are valid station names, but maybe this input field requires other Names

**Comment by CFenner** [comment]
Did you specify `origin` and `destination` or just 2x `destination`?

**Comment by Dom1n1c** [comment]
Well, that's an error by me, of course, I will test it later on, or tomorrow :)

**Comment by Dom1n1c** [comment]
Okay, i pasted a wrong section, but i entered Duesseldorf instead.
There is still one station left, i want to integrate, but i could use the places id instead.
(Station called: Hilden Süd/Talstraße ->ChIJbShUdGfNuEcRU7H41WscJ9M)
Whats a bit difficult right now: Maybe there is no Bus/Train departing due to christmas holidays
But the "/" sign and "ü" "ß" won't be recognized by the api.

and the subway icon is coloured, can i change it to monochrome?

**Comment by CFenner** [comment]
The icon comes from google directly, so I think not.

**Comment by CFenner** [comment]
You could use this [page](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-directions?hl=de), what suggestions do you get here for your origin/destination?

**Comment by Dom1n1c** [comment]
I will not further investigate it at this time. I will only show the connections to two bigger stations at this time.
