### ISSUE TITLE
Don't show similar connections

### ISSUE THREAD

**Issue by Dom1n1c** [CFenner/MagicMirror-LocalTransport-Module#14]
.. that have the same starting line.
its just a variation of the first route.
<img width="153" alt="similar" src="https://cloud.githubusercontent.com/assets/8407566/21481277/1a46e248-cb66-11e6-9374-8d037a58e503.PNG">

**Comment by GHLasse** [comment]
@Dom1n1c 
These are two valid options returned by Google which both work. i.e. if you miss the U74, you can still take the U79 and it takes just 1 minute longer. How exactly do you want to define similarity between routes and which of the two options should be removed?

I think it may be possible to specify waypoints (certain stops that your route has to pass). Would that help?

**Comment by Dom1n1c** [comment]
Since i am not able to get realtime data, i am using MMM-EFA-departures instead for single lines (direct transits from my station at home on selected lines)
