### ISSUE TITLE
Possibility to add module twice

### ISSUE THREAD

**Issue by ghost** [CFenner/MagicMirror-LocalTransport-Module#4]
When adding the module twice, origin and destination from the first module is also used for the second.

**Comment by schroedermatthias** [comment]
Hi @CFenner,
any idea what is happening here or what could be the reason?
My JS skills are not excellent, but maybe I can also try to investigate.

**Comment by schroedermatthias** [comment]
Hi @CFenner,
any idea what is happening here or what could be the reason?
My JS skills are not excellent, but maybe I can also try to investigate.

**Comment by CFenner** [comment]
Hi Matthias,

The module system should handle the separation of the config. Is this also happening for instance for the weather module?

**Comment by CFenner** [comment]
Ah no, I have an idea. The module is using a backend service, and this service notifies both widgets with the same information. I think I can fix this tonight.
