### ISSUE TITLE
Pulling direction from origin and destination input

### ISSUE THREAD

**Issue by bokifide** [CFenner/MagicMirror-LocalTransport-Module#7]
Hey,

I'm not sure if I'm missing something but I try to put my home address for origin and work address for destination and I can never seem get it to pull the information. It's suck on loading.. but when I add your example addresses it works..

Example:
origin: '233 Clarence Street, ON, Ottawa',
destination: '240 slater street, ON, Canada'

^ doesn't work.. What am I doing wrong?

**Comment by bokifide** [comment]
Somehow just started working.. I guess it just took about half an hour to load.

**Comment by CFenner** [comment]
So if I type your address in google maps, it changes it to: 
233 Clarence St, Ottawa, ON K1N 5R1, Kanada
240 Slater St, Ottawa, ON K1P, Kanada

Can you try that?
